# Generated by Django 2.2.2 on 2020-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=200)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
